# -*- coding: utf-8 -*-
"""Копия блокнота "Чат бот для постоянки"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VgtUy31Bjf-1bjSxDeG4LobLBcJUMyPG
"""

import requests
import json
import time

TOKEN = "vk1.a.jHaubHVmnjrNPn8iUD6phWqp0EpJILYubmGX07n_N5AYgPbeaC9pL9Ih6I7S9zex3DwUfyixXakbe_J2aKtxm1SnHQ_-kNgj1ZQ7-oMBMcQ3_LzTcZFf1iuim4INTidGvByahJjeS2OFcZhdOgboRvqPQ5LUHGfneBEVdl1dvUdI2u4WoK23oiB4DXsYorqHux89BiqeBvIKDMP3R0EqRQ"
GROUP_ID = 238365246

def send_msg(user_id, text, keyboard=None):
    params = {
        "user_id": user_id,
        "message": str(text)[:4000],
        "access_token": TOKEN,
        "v": "5.199",
        "random_id": int(time.time() * 1000)
    }
    if keyboard:
        params["keyboard"] = json.dumps(keyboard)
    r = requests.get("https://api.vk.com/method/messages.send", params=params)
    result = r.json()
    if "error" in result:
        print(f"❌ Ошибка: {result['error']['error_msg']}")
        return False
    print("✅")
    return True

def main_kb():
    return {
        "one_time": False,
        "buttons": [
            [{"action": {"type": "text", "label": "🏫 Кампус", "payload": '{"cmd":"campus"}'}}],
            [{"action": {"type": "text", "label": "📚 Учеба", "payload": '{"cmd":"study"}'}}],
            [{"action": {"type": "text", "label": "📄 Документы", "payload": '{"cmd":"documents"}'}}],
            [{"action": {"type": "text", "label": "🌟 Адаптация", "payload": '{"cmd":"adaptation"}'}}],
            [{"action": {"type": "text", "label": "❓ Вопрос", "payload": '{"cmd":"other"}'}}],
        ]
    }

def back_kb(back_to):
    return {
        "one_time": False,
        "buttons": [
            [{"action": {"type": "text", "label": "← Назад", "payload": f'{{"cmd":"{back_to}"}}'}}],
            [{"action": {"type": "text", "label": "🏠 Меню", "payload": '{"cmd":"menu"}'}}],
        ]
    }

def submenu_kb(items):
    btns = [[{"action": {"type": "text", "label": t, "payload": f'{{"cmd":"{c}"}}'}}] for t, c in items]
    btns.append([{"action": {"type": "text", "label": "🏠 Меню", "payload": '{"cmd":"menu"}'}}])
    return {"one_time": False, "buttons": btns}

WELCOME = "🎓 Добро пожаловать в университетский помощник! 🏫\n\nВыберите раздел:"

MENUS = {
    "campus": ("🏫 Кампус\nВыберите раздел:", [("📜 Правила проживания", "living"), ("🏨 Услуги гостиницы", "hotel"), ("🏛️ Услуги кампуса", "services")]),
    "study": ("📚 Учеба\nВыберите опцию:", [("📅 Расписание", "schedule"), ("💻 Электронные ресурсы", "online"), ("📝 Сессия и экзамены", "exams"), ("🎓 Академическая мобильность", "mobility")]),
    "documents": ("📄 Документы\nВыберите опцию:", [("📋 Справки и выписки", "cert"), ("🎫 Студенческий пропуск", "id_card"), ("📃 Академическая справка", "acad"), ("🔄 Восстановление", "restore")]),
    "adaptation": ("🌟 Адаптация\nДля новых студентов:", [("📱 Сим-карта", "sim"), ("💳 Банковская карта", "bank"), ("💰 Обмен валюты", "curr"), ("🌐 Соцсети", "soc"), ("🏠 Временная прописка", "reg")]),
    "hotel": ("🏨 Услуги гостиницы\nВыберите:", [("🧺 Прачечная", "laundry"), ("📶 Вай-фай", "wifi"), ("🔧 Ремонт", "repair")]),
    "services": ("🏛️ Услуги кампуса\nВыберите:", [("🍽️ Питание", "food"), ("🏋️ Спорт", "sport"), ("📚 Коворкинги", "cowork"), ("🛒 Бытовые услуги", "house"), ("🏥 Медицина", "med"), ("💰 Финансы", "fin")]),
}

TEXTS = {
    "living": "📜 Правила проживания в кампусе\n\n1. Время тишины: Будни 22:00-9:00, Выходные 23:00-10:00\n2. Посещение: Гости до 23:00, регистрация у охраны\n3. Безопасность: Курение в спецзонах\n4. Прачечная: запись через Poseidon",
    "laundry": "🧺 Прачечная в гостинице\n\n• Стиральные машины в каждом корпусе\n• Запись через сервис Poseidon (iOS/Android)\n• Нельзя стирать: кожу, мех, обувь",
    "wifi": "📶 Вай-фай в гостинице\n\n• Сеть: Rostelecom\n• Авторизация по номеру телефона",
    "repair": "🔧 Ремонт в гостинице\n\n• Онлайн-портал или лично у дежурного\n• За повреждения по вашей вине - плата",
    "food": "🍽️ Питание в кампусе\n\nСтоловые:\n• Корпус В, ур.4: 8:00-17:00 (Сб,Вс-вых)\n• Корпус 10, ур.1: 8:30-17:30 (ежедн)\n• Корпус 3, ур.1: 8:00-20:00 (ежедн)\n\nКафе:\n• Аякс (10:00-22:00)\n• Cofix (8:00-19:00)\n• Смарт Буфет (9:30-21:00)",
    "sport": "🏋️ Спортивные услуги\n\n• Бассейн: 8:00-22:00\n• Тренажерный зал: 7:00-23:00\n• Теннис, футбол, баскетбол\n\nЗапись в спортивном центре",
    "cowork": "📚 Коворкинги\n\n• Корпус А: «Аякс» ур.4, «Точки Кипения» ур.8, Библиотека ур.11\n• Корпус G: «Море внутри» ур.5\n• Корпус E: «РусГидро» ур.6",
    "house": "🛒 Бытовые услуги\n\n• Магазин: 8:00-23:00\n• Почта: Пн-Пт 10:00-18:00\n• Вендинговые автоматы в большинстве корпусов",
    "med": "🏥 Медицинские услуги\n\n• Поликлиника ДВФУ: круглосуточно\n• Тел: 8(423)239-77-00\n• Аптека: корп.7.2, Пн-Пт 9:00-20:00\n• Скорая: 103",
    "fin": "💰 Финансовые услуги\n\n• Банк: Корпус А, 6 этаж, Пн-Пт 10:00-18:00\n• Обмен валюты\n• Бесплатное обслуживание для студентов",
    "schedule": "📅 Расписание занятий\n\n• Онлайн: schedule.university.edu\n• Приложение: «Мой Университет»\n• Деканат: Корпус А, каб.301",
    "online": "💻 Электронные ресурсы\n\n• Библиотека: elibrary.university.edu\n• LMS: lms.university.edu\n• Бесплатно: Office 365, MATLAB, AutoCAD",
    "exams": "📝 Сессия и экзамены\n\n• Зимняя: январь-февраль\n• Летняя: июнь-июль\n• Пересдача: максимум 2 раза",
    "mobility": "🎓 Академическая мобильность\n\n• Отдел: Корпус D, каб.205\n• Email: mobility@university.edu",
    "cert": "📋 Справки и выписки\n\n• Для общежития, РВПО, визы\n• Об обучении, о стипендии\n• Медсправки: Медцентр ДВФУ",
    "id_card": "🎫 Студенческий пропуск\n\n• Выдается при поступлении\n• При утере: заявка на сайте",
    "acad": "📃 Академическая справка\n\n• Для перевода, восстановления\n• Учебный отдел: Корпус А, каб.302",
    "restore": "🔄 Восстановление документов\n\n• Студбилет, пропуск\n• Заявление на сайте → уведомление → получить",
    "sim": "📱 Сим-карта для студентов\n\n• Офисы операторов связи\n• Возьмите паспорт\n• Оформите в первую неделю!",
    "bank": "💳 Банковская карта\n\n• Документы: загранпаспорт, миграционная карта\n• Начните с онлайн-версии карты",
    "curr": "💰 Обмен валюты\n\n• Крупные банки через приложения\n• Сравнивайте курс!\n• Лучший курс обычно в будни утром",
    # ИСПРАВЛЕНО: убраны прямые ссылки, ВК их превращает в виджеты
    "soc": "🌐 Социальные сети университета\n\n📱 Telegram-канал: @fefudvfu\n👥 Группа ВКонтакте: tvoy_campus\n\nПодпишитесь, чтобы быть в курсе событий!",
    "reg": "🏠 Временная прописка\n\n• Паспортный стол: корп.8.2, каб.1.21\n• Пн,Ср,Пт 9:30-12:30 и 14:00-16:00\n• Срок: 3-7 дней\n\nИностранцам: миграционная карта, виза, перевод паспорта",
    "other": "❓ Связь с нами\n\n📞 +7(XXX)XXX-XX-XX\n📧 info@university.edu\n🏛️ Главный корпус, каб.228\n\nВсегда рады помочь! 😊",
}

BACKS = {
    "living": "campus", "laundry": "hotel", "wifi": "hotel", "repair": "hotel",
    "food": "services", "sport": "services", "cowork": "services",
    "house": "services", "med": "services", "fin": "services",
    "schedule": "study", "online": "study", "exams": "study", "mobility": "study",
    "cert": "documents", "id_card": "documents", "acad": "documents", "restore": "documents",
    "sim": "adaptation", "bank": "adaptation", "curr": "adaptation", "soc": "adaptation", "reg": "adaptation",
}

WORDS = {
    # Кампус
    "общежитие": "living", "проживание": "living",
    "прачечная": "laundry", "стирка": "laundry",
    "вайфай": "wifi", "wi-fi": "wifi", "интернет": "wifi",
    "ремонт": "repair", "поломка": "repair",
    "столовая": "food", "еда": "food", "кафе": "food", "питание": "food",
    "спорт": "sport", "бассейн": "sport", "тренажерный": "sport",
    "коворкинг": "cowork", "библиотека": "online",
    "магазин": "house", "почта": "house",
    "медицина": "med", "поликлиника": "med", "больница": "med", "аптека": "med", "врач": "med",
    "банк": "fin", "финансы": "fin", "деньги": "fin",

    # Учеба
    "учеба": "study", "расписание": "schedule", "занятия": "schedule", "пары": "schedule",
    "сессия": "exams", "экзамен": "exams", "зачет": "exams",
    "электронные": "online", "ресурсы": "online",
    "мобильность": "mobility", "стажировка": "mobility",

    # Документы
    "документ": "documents", "справка": "cert", "выписка": "cert",
    "пропуск": "id_card", "студенческий": "id_card",
    "восстановление": "restore", "потерял": "restore",

    # Адаптация
    "адаптация": "adaptation", "новичок": "adaptation", "первокурсник": "adaptation",
    "сим-карта": "sim", "симкарта": "sim",
    "банковская": "bank", "банковскую": "bank",
    "обмен": "curr", "валюта": "curr", "доллар": "curr", "евро": "curr",
    "соцсети": "soc", "социальные": "soc",
    "прописка": "reg", "регистрация": "reg", "миграцион": "reg",

    # Общее
    "контакты": "other", "связь": "other", "адрес": "other",
}

def process(user_id, text, payload=None):
    t = text.lower().strip()

    if t in ["/start", "начать", "меню", "привет", "/menu", "hi", "hello", "здравствуй"]:
        print("📤 Меню")
        return send_msg(user_id, WELCOME, main_kb())

    if t in ["/help", "помощь", "помоги"]:
        print("📤 Помощь")
        return send_msg(user_id, "🤖 Используйте кнопки меню или напишите слово: расписание, столовая, пропуск\n/start - главное меню", main_kb())

    if payload:
        try:
            cmd = json.loads(payload).get("cmd", "")
        except:
            return send_msg(user_id, "Ошибка кнопки", main_kb())

        print(f"📤 Кнопка: {cmd}")

        if cmd == "menu":
            return send_msg(user_id, WELCOME, main_kb())
        if cmd in MENUS:
            title, items = MENUS[cmd]
            return send_msg(user_id, title, submenu_kb(items))
        if cmd in TEXTS:
            return send_msg(user_id, TEXTS[cmd], back_kb(BACKS.get(cmd, "menu")))
        if cmd in BACKS:
            title, items = MENUS[BACKS[cmd]]
            return send_msg(user_id, title, submenu_kb(items))
        return send_msg(user_id, "Раздел не найден", main_kb())

    for word, cmd in WORDS.items():
        if word in t:
            print(f"📤 Слово: {word} → {cmd}")
            return process(user_id, text, json.dumps({"cmd": cmd}))

    print("📤 Не понял")
    return send_msg(user_id, "🤔 Не понял вопрос.\nИспользуйте кнопки меню или напишите: расписание, столовая\n/help - помощь", main_kb())

# ЗАПУСК
print("=" * 50)
print("🎓 УНИВЕРСИТЕТСКИЙ БОТ ВК")
print("=" * 50)

r = requests.get("https://api.vk.com/method/groups.getLongPollServer", params={
    "group_id": GROUP_ID, "access_token": TOKEN, "v": "5.199"
})

if "error" in r.json():
    print(f"❌ Ошибка подключения: {r.json()}")
else:
    data = r.json()["response"]
    server, key, ts = data["server"], data["key"], data["ts"]

    print(f"✅ Бот запущен!")
    print(f"📱 https://vk.com/club{GROUP_ID}")
    print(f"💬 Напишите /start в группу!")
    print("=" * 50)

    while True:
        try:
            url = f"{server}?act=a_check&key={key}&ts={ts}&wait=25"
            r = requests.get(url, timeout=30)
            data = r.json()

            if "failed" in data:
                print("🔄 Переподключение...")
                r = requests.get("https://api.vk.com/method/groups.getLongPollServer", params={
                    "group_id": GROUP_ID, "access_token": TOKEN, "v": "5.199"
                })
                server, key, ts = r.json()["response"]["server"], r.json()["response"]["key"], r.json()["response"]["ts"]
                continue

            ts = data.get("ts", ts)

            for update in data.get("updates", []):
                if update["type"] == "message_new":
                    msg = update["object"]["message"]
                    user_id = msg["from_id"]
                    text = msg["text"]
                    payload = msg.get("payload", None)

                    print(f"\n📨 {user_id}: {text}")
                    process(user_id, text, payload)
        except KeyboardInterrupt:
            print("\n🛑 Бот остановлен")
            break
        except Exception as e:
            print(f"⚠️ {e}")
            time.sleep(1)